cmake_minimum_required(VERSION 4.1.2)

if(NOT DEFINED aws_sdk_SOURCE_DIR)
  message(FATAL_ERROR "aws_sdk_SOURCE_DIR must be provided")
endif()

if(NOT DEFINED envy_cache_dir)
  message(FATAL_ERROR "envy_cache_dir must be provided")
endif()

set(_prefetch_script "${aws_sdk_SOURCE_DIR}/prefetch_crt_dependency.sh")
if(NOT EXISTS "${_prefetch_script}")
  message(FATAL_ERROR "Expected helper script missing: ${_prefetch_script}")
endif()

file(SHA256 "${_prefetch_script}" _aws_prefetch_hash)
file(SHA256 "${CMAKE_CURRENT_LIST_FILE}" _envy_prefetch_hash)
set(_stamp_value "${_aws_prefetch_hash}|${_envy_prefetch_hash}")

file(STRINGS "${_prefetch_script}" _prefetch_lines)
set(_crt_uri_prefix "")
set(_entry_specs "")
foreach(_line IN LISTS _prefetch_lines)
  string(REGEX REPLACE "#.*$" "" _line_no_comment "${_line}")
  string(STRIP "${_line_no_comment}" _trimmed)
  if(_trimmed STREQUAL "")
    continue()
  endif()
  if(_trimmed MATCHES "^CRT_URI_PREFIX=([^ \t]+)")
    set(_crt_uri_prefix "${CMAKE_MATCH_1}")
    continue()
  endif()
  if(_trimmed MATCHES "^([A-Z0-9_]+)=(.+)$")
    if(_crt_uri_prefix STREQUAL "")
      message(FATAL_ERROR "CRT_URI_PREFIX must appear before dependency URIs in ${_prefetch_script}")
    endif()
    set(_var "${CMAKE_MATCH_1}")
    if(NOT _var MATCHES "_URI$")
      continue()
    endif()
    if(NOT _trimmed MATCHES "/([^/]+)/zip/([0-9a-f]+)")
      message(FATAL_ERROR "Malformed URI in ${_prefetch_script}: ${_trimmed}")
    endif()
    set(_repo "${CMAKE_MATCH_1}")
    set(_commit "${CMAKE_MATCH_2}")
    set(_uri "${_crt_uri_prefix}/${_repo}/zip/${_commit}")
    list(APPEND _entry_specs "${_var}|${_uri}|${_repo}|${_commit}")
  endif()
endforeach()

if(_entry_specs STREQUAL "")
  message(FATAL_ERROR "Failed to parse dependency URIs from ${_prefetch_script}")
endif()

set(_main_repo "")
set(_main_commit "")
set(_main_uri "")
set(_dependency_repos "")
set(_download_specs "")
foreach(_spec IN LISTS _entry_specs)
  string(REPLACE "|" ";" _parts "${_spec}")
  list(GET _parts 0 _name)
  list(GET _parts 1 _uri)
  list(GET _parts 2 _repo)
  list(GET _parts 3 _commit)
  if(_name STREQUAL "CRT_URI")
    set(_main_repo "${_repo}")
    set(_main_commit "${_commit}")
    set(_main_uri "${_uri}")
  else()
    list(APPEND _dependency_repos "${_repo}")
  endif()
  list(APPEND _download_specs "${_repo}|${_commit}|${_uri}|${_name}")
endforeach()

if(_main_uri STREQUAL "")
  message(FATAL_ERROR "prefetch_crt_dependency.sh did not define CRT_URI")
endif()

set(_crt_parent "${aws_sdk_SOURCE_DIR}/crt")
set(_crt_root "${_crt_parent}/${_main_repo}")
set(_stamp_file "${_crt_parent}/.envy-crt-stamp")

set(_need_refresh ON)
if(EXISTS "${_crt_root}/CMakeLists.txt" AND EXISTS "${_stamp_file}")
  file(READ "${_stamp_file}" _existing_stamp)
  string(STRIP "${_existing_stamp}" _existing_stamp)
  if(_existing_stamp STREQUAL "${_stamp_value}")
    set(_need_refresh OFF)
    foreach(_repo IN LISTS _dependency_repos)
      if(NOT EXISTS "${_crt_root}/crt/${_repo}")
        set(_need_refresh ON)
        break()
      endif()
    endforeach()
    if(NOT EXISTS "${_crt_root}/crt/s2n" AND EXISTS "${_crt_root}/crt/s2n-tls")
      set(_need_refresh ON)
    endif()
  endif()
endif()

if(NOT _need_refresh)
  return()
endif()

message(STATUS "[envy] Prefetching AWS CRT dependencies via CMake")

set(_fully_disconnected FALSE)
if(DEFINED FETCHCONTENT_FULLY_DISCONNECTED AND FETCHCONTENT_FULLY_DISCONNECTED)
  set(_fully_disconnected TRUE)
elseif(DEFINED ENV{ENVY_FETCH_FULLY_DISCONNECTED})
  string(TOUPPER "$ENV{ENVY_FETCH_FULLY_DISCONNECTED}" _env_flag)
  if(NOT _env_flag STREQUAL "" AND
     NOT _env_flag STREQUAL "0" AND
     NOT _env_flag STREQUAL "OFF" AND
     NOT _env_flag STREQUAL "FALSE")
    set(_fully_disconnected TRUE)
  endif()
endif()

cmake_path(APPEND envy_cache_dir "aws-crt" OUTPUT_VARIABLE _cache_root)
file(MAKE_DIRECTORY "${_cache_root}")

set(_main_archive "")
set(_dependency_archives "")
foreach(_spec IN LISTS _download_specs)
  string(REPLACE "|" ";" _parts "${_spec}")
  list(GET _parts 0 _repo)
  list(GET _parts 1 _commit)
  list(GET _parts 2 _uri)
  set(_archive_path "${_cache_root}/${_repo}-${_commit}.zip")
  if(NOT EXISTS "${_archive_path}")
    if(_fully_disconnected)
      message(FATAL_ERROR
        "[envy] Missing cached archive for ${_repo} (${_commit}) while fully disconnected: ${_archive_path}")
    endif()
    set(_tmp_path "${_archive_path}.partial")
    file(REMOVE "${_tmp_path}")
    message(STATUS "[envy] Downloading ${_repo} (${_commit})")
    file(DOWNLOAD "${_uri}" "${_tmp_path}"
      SHOW_PROGRESS
      STATUS _download_status
      TLS_VERIFY ON)
    list(GET _download_status 0 _status_code)
    if(NOT _status_code EQUAL 0)
      file(REMOVE "${_tmp_path}")
      list(LENGTH _download_status _status_len)
      if(_status_len GREATER 1)
        list(GET _download_status 1 _status_msg)
      else()
        set(_status_msg "unknown error")
      endif()
      message(FATAL_ERROR "Failed to download ${_repo} (${_commit}): ${_status_msg}")
    endif()
    file(RENAME "${_tmp_path}" "${_archive_path}")
  endif()
  if(_repo STREQUAL "${_main_repo}" AND _commit STREQUAL "${_main_commit}")
    set(_main_archive "${_archive_path}")
  else()
    list(APPEND _dependency_archives "${_archive_path}")
  endif()
endforeach()

if(NOT EXISTS "${_main_archive}")
  message(FATAL_ERROR "Unable to locate aws-crt-cpp archive '${_main_repo}-${_main_commit}.zip'")
endif()

set(_stage_root "${_crt_parent}/.envy-crt-stage")
set(_stage_tmp "${_stage_root}/tmp")
file(REMOVE_RECURSE "${_stage_root}")
file(MAKE_DIRECTORY "${_stage_tmp}")

file(ARCHIVE_EXTRACT INPUT "${_main_archive}" DESTINATION "${_stage_root}")
file(GLOB _main_candidates LIST_DIRECTORIES TRUE "${_stage_root}/${_main_repo}*")
if(_main_candidates STREQUAL "")
  message(FATAL_ERROR "Extraction of ${_main_repo} did not produce an ${_main_repo} directory")
endif()
list(SORT _main_candidates)
list(GET _main_candidates 0 _main_extracted)
set(_crt_stage_dir "${_stage_root}/${_main_repo}")
if(NOT "${_main_extracted}" STREQUAL "${_crt_stage_dir}")
  if(EXISTS "${_crt_stage_dir}")
    file(REMOVE_RECURSE "${_crt_stage_dir}")
  endif()
  file(RENAME "${_main_extracted}" "${_crt_stage_dir}")
endif()
set(_crt_stage_crt_dir "${_crt_stage_dir}/crt")
file(REMOVE_RECURSE "${_crt_stage_crt_dir}")
file(MAKE_DIRECTORY "${_crt_stage_crt_dir}")

foreach(_archive IN LISTS _dependency_archives)
  file(ARCHIVE_EXTRACT INPUT "${_archive}" DESTINATION "${_stage_tmp}")
endforeach()

file(GLOB _tmp_dirs LIST_DIRECTORIES TRUE "${_stage_tmp}/*")
list(SORT _tmp_dirs)
foreach(_dir IN LISTS _tmp_dirs)
  if(NOT IS_DIRECTORY "${_dir}")
    continue()
  endif()
  get_filename_component(_entry_name "${_dir}" NAME)
  if(_entry_name MATCHES "\\.zip$")
    continue()
  endif()
  string(REGEX REPLACE "-[0-9a-fA-F]+$" "" _trimmed "${_entry_name}")
  if(_trimmed STREQUAL "")
    set(_trimmed "${_entry_name}")
  endif()
  if(_trimmed STREQUAL "${_main_repo}")
    continue()
  endif()
  set(_dest "${_crt_stage_crt_dir}/${_trimmed}")
  if(EXISTS "${_dest}")
    file(REMOVE_RECURSE "${_dest}")
  endif()
  file(RENAME "${_dir}" "${_dest}")
endforeach()

file(REMOVE_RECURSE "${_stage_tmp}")

set(_s2n_tls_dir "${_crt_stage_crt_dir}/s2n-tls")
if(EXISTS "${_s2n_tls_dir}")
  set(_s2n_dir "${_crt_stage_crt_dir}/s2n")
  if(EXISTS "${_s2n_dir}")
    file(REMOVE_RECURSE "${_s2n_dir}")
  endif()
  file(RENAME "${_s2n_tls_dir}" "${_s2n_dir}")
endif()

file(MAKE_DIRECTORY "${_crt_parent}")
if(EXISTS "${_crt_root}")
  file(REMOVE_RECURSE "${_crt_root}")
endif()
if(EXISTS "${_crt_parent}/tmp")
  file(REMOVE_RECURSE "${_crt_parent}/tmp")
endif()
file(RENAME "${_crt_stage_dir}" "${_crt_root}")
file(REMOVE_RECURSE "${_stage_root}")

file(WRITE "${_stamp_file}" "${_stamp_value}\n")

unset(_prefetch_lines)
unset(_entry_specs)
unset(_download_specs)
unset(_dependency_repos)
unset(_main_archive)
unset(_dependency_archives)
unset(_main_candidates)
unset(_tmp_dirs)
