cmake_minimum_required(VERSION 3.18)

if(NOT DEFINED OPENSSH_SOURCE_DIR)
    message(FATAL_ERROR "OPENSSH_SOURCE_DIR not provided to PatchOpenSSH.cmake")
endif()

set(_configure "${OPENSSH_SOURCE_DIR}/configure")
if(EXISTS "${_configure}")
    file(READ "${_configure}" _cfg)
    set(_needle "301*|302*|303*")
    set(_replacement "301*|302*|303*|304*|305*|306*|307*|308*|309*")
    string(REPLACE "${_needle}" "${_replacement}" _patched "${_cfg}")
    if(NOT _cfg STREQUAL _patched)
        file(WRITE "${_configure}" "${_patched}")
    endif()
endif()

set(_configure_ac "${OPENSSH_SOURCE_DIR}/configure.ac")
if(EXISTS "${_configure_ac}")
    file(READ "${_configure_ac}" _cfg_ac)
    string(REPLACE "301*|302*|303*" "301*|302*|303*|304*|305*|306*|307*|308*|309*" _patched_ac "${_cfg_ac}")
    if(NOT _cfg_ac STREQUAL _patched_ac)
        file(WRITE "${_configure_ac}" "${_patched_ac}")
    endif()
endif()
